// docs-build/src/components/RightSidebar/TableOfContents.svelte
<script>
  export let headers = []
</script>

{#if headers.length}
  <h2 class="heading">On this page</h2>
  <ul>
    <li class="header-link depth-2">
      <a href="#overview">Overview</a>
    </li>
    {#each headers as header}
      {#if header.depth > 1 && header.depth < 4}
        <li class={`header-link depth-${header.depth}`}>
          <a href={`#${header.slug}`}>{header.text}</a>
        </li>
      {/if}
    {/each}
  </ul>
{/if}

// docs-build/src/components/RightSidebar/TableOfContents.tsx
import type { FunctionalComponent } from "preact"
import { h, Fragment } from "preact"
import { useState, useEffect, useRef } from "preact/hooks"

const TableOfContents: FunctionalComponent<{ headers: any[] }> = ({
  headers = [],
}) => {
  const itemOffsets = useRef([])
  const [activeId, setActiveId] = useState<string>(undefined)

  useEffect(() => {
    const getItemOffsets = () => {
      const titles = document.querySelectorAll("article :is(h1, h2, h3, h4)")
      itemOffsets.current = Array.from(titles).map((title) => ({
        id: title.id,
        topOffset: title.getBoundingClientRect().top + window.scrollY,
      }))
    }

    getItemOffsets()
    window.addEventListener("resize", getItemOffsets)

    return () => {
      window.removeEventListener("resize", getItemOffsets)
    }
  }, [])
  if (!headers.length) {
    return null
  }

  return (
    <>
      <h2 class="heading">On this page</h2>
      <ul>
        <li
          class={`header-link depth-2 ${
            activeId === "overview" ? "active" : ""
          }`.trim()}
        >
          <a href="#overview">Overview</a>
        </li>
        {headers
          .filter(({ depth }) => depth > 1 && depth < 4)
          .map((header) => (
            <li
              class={`header-link depth-${header.depth} ${
                activeId === header.slug ? "active" : ""
              }`.trim()}
            >
              <a href={`#${header.slug}`}>{header.text}</a>
            </li>
          ))}
      </ul>
    </>
  )
}

export default TableOfContents
